project:
  type: website

website:
  title: "Stephan König"
  description: "A personal website"
  site-url: "https://stephankoenig.me"
  twitter-card: true
  open-graph: true
  cookie-consent: true
  google-analytics:
    tracking-id: "G-9MT8R5PS1Y"
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - about.qmd
    right:
      - icon: mastodon
        aria-label: "Mastodon"
        href: "https://fosstodon.org/@stephankoenig"
      - icon: github
        aria-label: "GitHub"
        href: "https://github.com/stephan-koenig"
      - icon: linkedin
        aria-label: "LinkedIn"
        href: "https://www.linkedin.com/in/stephan-koenig"
      # - text: "{{< fa brands researchgate size=lg >}}"
      #   href: "https://www.researchgate.net/profile/Stephan-Koenig-6"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

bibliography: references.bib
csl: apa-cv.csl

execute:
  freeze: auto

editor: visual
