[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.105.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'


[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  # Do not fail the build if a11y issues are found
  resultMode = "warn"
    
[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  # Do not fail the build if any issues with links are found
  todoPatterns = [
    "load",
  ]

[[plugins]]
package = "netlify-plugin-inline-critical-css"
